### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by JohnMcLear** [JohnMcLear/ep_mammoth#4]
Causes server crash

```
[2015-04-20 15:03:06.562] [ERROR] console - Error: Non-whitespace before first tag.
    at error (/home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/node_modules/sax/lib/sax.js:642:8)
    at strictFail (/home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/node_modules/sax/lib/sax.js:662:22)
    at Object.write (/home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/node_modules/sax/lib/sax.js:934:11)
    at Object.read (/home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/lib/xmlreader.js:75:12)
    at read (/home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/lib/office-xml-reader.js:19:22)
    at _fulfilled (/home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/node_modules/q/q.js:760:13)
    at /home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/node_modules/q/q.js:574:44
    at flush (/home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/node_modules/q/q.js:108:17)
```
Not sure on STR

**Comment by JohnMcLear** [comment]
Should be fixed with mammoth verison bump
